Basic:
  date_from: ['2009-01-05']
  date_to: ['2020-12-31']
  type_: ['stocks_index_cn']
  comment: ['cn_data']
  mode: ['end-to-end']
  dim1: [96]
  dim2: [64]
  risk_levels: [5]
  pred_type: ['y_0']
  window_size: [256]
  num_samples: [50]
  test_type: ['denoising']
  timesteps: [500] # [100, 300, 500]
  train_epochs: [400]
  batch_size: [128]
  test_batch_size: [128]
  patience: [25]
  learning_rate: [5.0e-3] # [5e-5, 1.0e-4, 5.0e-4]